### ISSUE TITLE
Running this repository with `sbt` throws error

### ISSUE THREAD

**Issue by greninja** [koksal/sbl#1]
Hi @koksal,

From the root directory of the project, I ran `sbt "run --solve"` which went through successfully.
But I want to run `sbt "run --summarize"` to get the output of TraceSummarization.scala. Unfortunately
it throws the following error : 

```
shadab@hp:~/Downloads/sbl$ sbt "run --summarize"
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Set current project to sbl (in build file:/home/shadab/Downloads/sbl/)
[info] Running elegans.Main --summarize
Loading scalaz3
[ERROR] Sanity check for symbolic run: FAILED
[ERROR] sanity check fails
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 5 s, completed May 3, 2018 3:09:23 PM
shadab@hp:~/Downloads/sbl$ 
```

**Comment by koksal** [comment]
Shadab, first of all, glad to hear you could run the synthesis workflow as intended with the `run --solve` option.

Trace summarization was an experimental feature we briefly worked on, but ended up not including in our published work. It is meant to be run with a "solution" file, which is why you encountered this error.

**Comment by greninja** [comment]
Dear Ali,

Thanks for your reply. Quick questions:
1) So you did not try running with the `--summarize` option at all?
2) Secondly, could you give a very brief overview of what the rational behind Trace Summarization is?

Many thanks,
Shadab
